server:
  port: 8888

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # 数据源的相关配置
    driver-class-name: com.mysql.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=utf-8 # 数据库连接地址
    username: root # 数据库用户名
    password: root # 数据库密码
    hikari:
      connection-timeout:  3000 # 连接超时时间
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 10 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 60000 # 空闲连接超时时间
      max-lifetime: 1800000 # 连接的最大生命周期
      connection-test-query: SELECT 1 # 测试连接的sql语句
      pool-name: DataSourceHikariCP # 连接池名称

